- name: setup backend
  hosts: all
  become: yes
  tasks:
    - name: disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: copy the backend service
      ansible.builtin.copy:
        name: backend.service
        dest: /etc/systemd/system/backend.service

    - name: adding application user
      ansible.builtin.user:
        name: expense

    - name: removing the existing app content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: creating directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download and extract the application content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: download dependencies
      community.general.npm:
        path: /app

    - name: reload the systemd and restart the backend
      ansible.builtin.systemd_service:
        name: backend
        state: restarted
        enable: yes

    - name: install mysql
      ansible.builtin.dnf:
        src: mysql
        state: installed

    - name: load schema
      community.mysql.mysql_db:
          state: import
          name: all
          target: /app/schema/backend.sql
          login_user: root
          login_password: ExpenseApp@1
          login_host: mysql-dev.narendrat.online






