
    - name: disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: copy the backend service
      ansible.builtin.templates:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: adding application user
      ansible.builtin.user:
        name: expense

    - name: app_prequests
      ansible.builtin.include_role:
        name: common
        tasks_from: app_request



    - name: download dependencies
      community.general.npm:
        path: /app

    - name: reload the systemd and restart the backend
      ansible.builtin.systemd_service:
        name: backend
        state: restarted
        enabled: yes


    - name: install mysql & python library for mysql
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: installed
      loop:
        - mysql
        - python3-PyMySQL


    - name: load schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: "{{ lookup('amazon.aws.aws_ssm', 'dev.mysql.root_password', region= 'us-east-1' ) }}"
        login_host: mysql-dev.narendrat.online






