
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: copy expense conf file
      ansible.builtin.template:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: app_prequests
      ansible.builtin.include_role:
        name: common
        tasks_from: app_request


    - name: start nginx
      ansible.builtin.systemd_service:
        name: nginx
        enabled: yes
        state: restarted


