  - name: disable mysql default version
    ansible.builtin.shell: dnf module disable mysql -y

  - name: copy mysql repo file
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: install mysql
    ansible.builtin.dnf:
      name:  mysql-community-server
      state: installed

  - name: start mysql service
    ansible.builtin.systemd_service:
      name: mysqld
      state: restarted

  - name: set mysql root password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
