format_version: 10
pipelines:
 deploy:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/NARENDRA935/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - test-stage:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - -A